name: 🚀 Deploy File to cPanel via SSH

on:
  push:
    branches:
      - main

jobs:
  SSH-Deploy-Action:
    name: 🎉 Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 🔨 Install Dependencies and Build
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install --force
          npm install axios --save
          npm run build
          git reset --hard
        env:
          CI: false

      - name: List Files
        run: ls -R

      - name: 📂 Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/admin.lovebird4u.com || exit 1
            rm -rf *  # Remove all existing files
            rsync -avz --exclude='.git' ./build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/admin.lovebird4u.com || exit 1
            pm2 restart lovebird-admin-site || exit 1
            pm2 save || exit 1
