name: 🚀 Deploy File to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 🔨 Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install --force
          npm install axios --save
          npm run build
          git reset --hard
        env:
         CI: false
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              key: ${{ secrets.SERVER_SSH_KEY }}
              port: 22
              local-dir: build/
              server-dir: /var/www/admin.lovebird4u.com/
        # with:
        #   host: ${{ secrets.SERVER_HOST }}  # Your VPS IP or hostname
        #   username: ${{ secrets.SERVER_USER }}  # SSH username (e.g., root)
        #   key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key
        #   port: 22
        #   script: |
        #     cd /var/www/admin.lovebird4u.com || exit 1
        #     rm -rf *  # Remove all existing files
        #     rsync -avz --exclude='.git' ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/admin.lovebird4u.com || exit 1
        #     pm2 restart lovebird-admin-site || exit 1
        #     pm2 save || exit 1
